/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pooaula1;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pooaula1.Pessoa;
import pooaula1.SumarioPessoa;

/**
 * 
 *
 * @author fabiomacz
 */
public class TelaPrincipal extends javax.swing.JFrame {
    Date dataNascimento = null;
    //Criar Lista Pessoas
    ArrayList<Pessoa> pessoas = new ArrayList<>();
    /**
     * Creates new form Frame
     */
    public TelaPrincipal() {
        initComponents();
        txtNome.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        ftxtDataNascimento = new javax.swing.JFormattedTextField();
        btnCadastrar = new javax.swing.JButton();
        btnSumarizar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnListarPessoas = new javax.swing.JButton();
        btnLimparLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setText("Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 51, -1, -1));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 48, 176, -1));

        lblDataNascimento.setText("Data Nascimento");
        jPanel1.add(lblDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 86, -1, -1));

        try {
            ftxtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtDataNascimentoFocusLost(evt);
            }
        });
        jPanel1.add(ftxtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 83, 124, -1));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 152, 110, -1));

        btnSumarizar.setText("Sumarizar");
        btnSumarizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSumarizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 48, 110, -1));

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 152, 110, -1));

        btnListarPessoas.setText("Listar Pessoas");
        btnListarPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPessoasActionPerformed(evt);
            }
        });
        jPanel1.add(btnListarPessoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 19, 110, -1));

        btnLimparLista.setText("Limpar Lista");
        btnLimparLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimparLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 80, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome = txtNome.getText();
        if (nome.isBlank()) {
            JOptionPane.showMessageDialog(this, "Informe o nome");
            txtNome.requestFocus();
        } else if (dataNascimento == null) {
            JOptionPane.showMessageDialog(this, "Informe uma data de nascimento válida.");
            ftxtDataNascimento.requestFocus();
        } else {
            Pessoa p = new Pessoa(); // Criar objeto da classe pessoa
            p.nome = txtNome.getText();
            p.dataNascimento = dataNascimento;
            pessoas.add(p); //adicionar a lista
            JOptionPane.showMessageDialog(this, "Nome: " + txtNome.getText() +
                "\nData de Nascimento: " + ftxtDataNascimento.getText());
            txtNome.setText("");
            ftxtDataNascimento.setValue(null);
            txtNome.requestFocus();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void ftxtDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtDataNascimentoFocusLost
        boolean erro = true;
        dataNascimento = null;
        String dataTexto = ftxtDataNascimento.getText();
        //Converter de String para Date
        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
        formatoData.setLenient(false);
        try {
            dataNascimento = formatoData.parse(dataTexto);
            Calendar dataNasc = Calendar.getInstance();
            dataNasc.setTime(dataNascimento);
            Calendar hoje = Calendar.getInstance();
            hoje.getTime();
            if (hoje.after(dataNasc) || hoje.equals(dataNasc)) {
                erro = false;
            }

        } catch (ParseException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (erro) {
            dataNascimento = null;
            JOptionPane.showMessageDialog(this, "Data Inválida: " + dataTexto);
            ftxtDataNascimento.requestFocus();
        }
    }//GEN-LAST:event_ftxtDataNascimentoFocusLost

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSumarizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarizarActionPerformed
        if (pessoas.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Não há pessoas cadastradas!");
        } else {
            SumarioPessoa sumario = new SumarioPessoa();
            sumario.sumarizar(pessoas);
            JOptionPane.showMessageDialog(this,
                    "Qtde: " + sumario.cont
                    + "\nQtde de Pessoas de Maior: " + sumario.contMaior
                    + "\nQtde de Pessoas de Menor: " + sumario.contMenor
                    + "\nMaior Idade: " + sumario.maior
                    + "\nPessoa com Maior Idade: " + sumario.nomeMaior
                    + "\nMenor Idade: " + sumario.menor
                    + "\nPessoa com Menor Idade: " + sumario.nomeMenor
                    + "\nMédia das Idades: " + sumario.media
                    + "\nPercentual de Pessoas de Maior: " + sumario.percMaior
                    + "\nPercentual de Pessoas de Menor: " + sumario.percMenor
            );
        }

    }//GEN-LAST:event_btnSumarizarActionPerformed

    private void btnListarPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPessoasActionPerformed
       if (pessoas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não há pessoas cadastradas!");
        } else {
            /*String msg = "";
            for (Pessoa p : pessoas) {
                msg = msg + p.imprimir() + "\n\n";
            }
            JOptionPane.showMessageDialog(this, msg); */
            
            new TelaListaPessoas(pessoas).setVisible(true);
        }
    }//GEN-LAST:event_btnListarPessoasActionPerformed

    private void btnLimparListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparListaActionPerformed
        // TODO add your handling code here:
        pessoas.clear();
        JOptionPane.showMessageDialog(this, "Lista Apagada!");
    }//GEN-LAST:event_btnLimparListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimparLista;
    private javax.swing.JButton btnListarPessoas;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSumarizar;
    private javax.swing.JFormattedTextField ftxtDataNascimento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
